apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  
 ###nodeport###
  
# apiVersion: v1
# kind: Service
# metadata:
#   name: wordpress
#   labels:
#     app: wordpress
# spec:
#   selector:
#     app: wordpress
#     tier: frontend
#   type: NodePort
#   ports:
#     - nodePort: 30007 
#       port: 80
#       targetPort: 80